service: gateway-test

provider:
  name: aws
  endpointType: edge
  stage: ${opt:stage, 'dev'}
  runtime: nodejs14.x
  region: eu-west-2
  iamRoleStatements:
    - Effect: Allow
      Action: 'ec2:*'
      Resource: "*"
  apiGateway:
    apiKeySourceType: HEADER
    minimumCompressionSize: 1024
    description: This is the description, idk where it goes

functions:
  app:
    handler: app.handler
    events:
      - http:
          path: /v1/{proxy+}
          method: any
          integration: lambda-proxy
          authorizer:
            arn: arn:aws:cognito-idp:eu-west-2:493235065205:userpool/eu-west-2_8yI8I0Raa
  authenticate:
    handler: app.authHandler
    events:
      - http:
          path: /authenticate
          method: any
          integration: lambda-proxy
  register:
    handler: app.registrationHandler
    events:
      - http:
          path: /register
          method: any
          integration: lambda-proxy

    