service: gateway-test

provider:
  name: aws
  endpointType: edge
  stage: ${opt:stage, 'dev'}
  runtime: nodejs14.x
  region: eu-west-2
  iamRoleStatements:
    - Effect: Allow
      Action: 'ec2:*'
      Resource: "*"
  apiGateway:
    apiKeySourceType: HEADER
    minimumCompressionSize: 1024
    description: This is the description, idk where it goes

functions:
  action:
    handler: app.handler
    events:
      - http:
          path: /action/{proxy+}
          method: any
          integration: lambda-proxy
  authenticate:
    handler: app.handler
    events:
      - http:
          path: /authenticate/{proxy+}
          method: any
          integration: lambda-proxy
  register:
    handler: app.handler
    events:
      - http:
          path: /register/{proxy+}
          method: any
          integration: lambda-proxy
  api:
    handler: app.handler
    events:
      - http:
          path: /v1/{proxy+}
          method: any
          integration: lambda-proxy
